[package]
name = "fah-stats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fah-rules = { path = "../fah-rules" }
fah-model = { path = "../fah-model" }
fah-config = { path = "../fah-config" }
fah-common = { path = "../fah-common" }
fah-logging = { path = "../fah-logging" }
